### ISSUE TITLE
Separation of Concerns

### ISSUE THREAD

**Issue by jordanwillis** [sijya/prj-rev-bwfs-dasmoto#2]
Another big recommendation that I would make is to always maintain the separation of concerns between the structure of your document (HTML) and the style of your document (CSS) by not using the size or other style related element attributes.

https://github.com/sijya/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L13
https://github.com/sijya/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L19
https://github.com/sijya/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L25

In these `<img>` elements you are using both `height` and `width`.  While this is technically not a problem, it muddies the waters between where the styling information is located.  It is much easier to maintain if all of this is kept in the same place, plus it can prevent confusion in case you set these attributes in your HTML but also add conflicting properties in your CSS.

Instead, you should just use the `height` and `width` property in CSS on a selector that matches the `<img>` element.

**Comment by sijya** [comment]
Ah okay, thats super insightful, thank you so much!
